repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
    # Run the linter.
      - id: ruff
        args: [ --fix ]
    # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8 # Update me!
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
  - repo: https://github.com/rubik/xenon
    rev: v0.9.0
    hooks:
      - id: xenon
        args: [ --max-absolute B, --max-modules A, --max-average A ]
  - hooks:
      - id: flake8
        args:
          - "--max-line-length=99"
    repo: https://github.com/pycqa/flake8
    rev: 6.1.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - args:
          - --django
        id: name-tests-test
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-docstring-first
      - id: sort-simple-yaml
      - id: check-toml
      - id: check-merge-conflict
